--DROP TABLE IF EXISTS Niveis;

DROP TABLE IF EXISTS teste;

DROP TABLE IF EXISTS Professor;

DROP TABLE IF EXISTS lod;

DROP TABLE IF EXISTS lois;

DROP TABLE IF EXISTS medalha;

DROP TABLE IF EXISTS medalhas;

DROP TABLE IF EXISTS testesd;
